Traceback (most recent call last):
  File "C:\Users\BAGUS\PYTHON\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\BAGUS\PYTHON\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BAGUS\PYTHON\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BAGUS\PYTHON\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\BAGUS\PYTHON\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\BAGUS\PYTHON\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\BAGUS\PYTHON\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# !pip install mysql-connector-python  # untuk install module mysql connector, uncomment untuk install
import mysql.connector
import pandas as pd

# Informasi koneksi ke database MySQL di cloud aiven
hostname = 'database2-bagus22081.a.aivencloud.com'
port = 24084
username = 'avnadmin'
password = 'AVNS_e2gyqyxIQVG7Vqu7BrF'
database = 'iris'

# Membuat koneksi ke database MySQL
conn = mysql.connector.connect(
    host=hostname,
    port=port,
    user=username,
    password=password,
    database=database
)

# Membaca data dari database menggunakan Pandas
query = "SELECT * FROM iris_dataset_pure"
dataset = pd.read_sql(query, conn)

# Menutup koneksi ke database
conn.close()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 2[0m
[0;32m      1[0m [38;5;66;03m# !pip install mysql-connector-python  # untuk install module mysql connector, uncomment untuk install[39;00m
[1;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmysql[39;00m[38;5;21;01m.[39;00m[38;5;21;01mconnector[39;00m
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m      5[0m [38;5;66;03m# Informasi koneksi ke database MySQL di cloud aiven[39;00m

[1;31mModuleNotFoundError[0m: No module named 'mysql'

